name: Android CI

#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "main" ]

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  version-bump:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions: {actions: write}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version
        id: bump_version
        uses: oflynned/Android-Semantic-Release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      #
      #      - name: build debug
      #        run: ./gradlew assembleDebug

      - name: build Build
        run: ./gradlew build

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true # optional (default = false)
          files: ./musica-phone/build/reports/kover/reportDebug.xml,./musica-common/build/reports/kover/reportDebug.xml,./dashboard-module/build/reports/kover/reportDebug.xml
        #          flags: unittests # optional
        #          name: codecov-umbrella # optional
        #          verbose: true # optional (default = false)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          #          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: musica-phone/build/outputs/apk/debug/musica-phone-debug.apk
