name: Distribute to Firebase App Distribution

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build & Distribute
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  # Match your project's version

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Create Firebase service account JSON file
        run: echo "$FIREBASE_SERVICE_ACCOUNT_JSON" > ${{ github.workspace }}/firebase-service-account.json
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}

      - name: Run Gradle app distribution upload
        run: ./gradlew appDistributionUploadDebug
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-service-account.json

